### ISSUE TITLE
[Feat] 항공권 리스트 Nav

### ISSUE THREAD

**Issue by se0jinYoon** [DO-SOPT-CDS-TEAM-WEB7/Client#3]
## 🛠 Issue
항공권(티켓)리스트 Header
<img width="846" alt="스크린샷 2023-11-24 오전 8 48 56" src="https://github.com/DO-SOPT-CDS-TEAM-WEB7/Client/assets/109661444/02a2666a-061a-414b-a4d2-998039b49df9">

## 

## 📝 To-do

- [x] Skyscanner 로고 이미지 추출
- [x] 항공권, 호텔, 렌터카, 검색 아이콘 추출
- [x] 언어 변환 선택바
- [x] 도움말, 위시리스트, 로그인 선택바
- [x] 항공권, 호텔, 렌터카 선택바
- [x] main branch 변경사항 반영
- [x] 배경색 넣기
