### ISSUE TITLE
[Feat] 항공권 리스트 nav바 상단, 하단 이미지

### ISSUE THREAD

**Issue by se0jinYoon** [DO-SOPT-CDS-TEAM-WEB7/Client#36]
## 🛠 Issue

<img width="735" alt="스크린샷 2023-11-29 오후 4 52 36" src="https://github.com/DO-SOPT-CDS-TEAM-WEB7/Client/assets/109661444/72d2f8ad-5d27-4fb6-a0f4-e4927210c6c3">

여기 뒤에 비행기, 광고 이미지 삽입

## 📝 To-do

- [x] 배경 비행기 이미지 삽입 (z-index)
- [x] 광고 이미지 삽입  
- [x] nav바 폰트 스타일 수정
