### ISSUE TITLE
[Feat] 항공권 리스트 캐러셀

### ISSUE THREAD

**Issue by se0jinYoon** [DO-SOPT-CDS-TEAM-WEB7/Client#4]
## 
항공권 리스트 캐러셀
## 📝 To-do

- [ ] 캐러셀 라이브러리 설치
- [ ] 캐러셀 라이브러리 커스텀
- [ ] 캐러셀에 반복적으로 사용될 레이아웃 컴포넌트 정의
