### ISSUE TITLE
[Feat] GET API로 최저가 항공 섹션 구현

### ISSUE THREAD

**Issue by aazkgh** [DO-SOPT-CDS-TEAM-WEB7/Client#40]
## 🛠 Issue

API를 불러와서 최저가 항공 섹션을 구현하기

## 📝 To-do

- [ ] 최저가 항공 컴포넌트 여러 개로 갤러리 구현
- [ ] 타이틀과 함께 총 섹션 구현
- [ ] GET API를 통해 데이터 불러오기
