### ISSUE TITLE
[Feat] 항공권 리스트 비행기 티켓 API 연결

### ISSUE THREAD

**Issue by se0jinYoon** [DO-SOPT-CDS-TEAM-WEB7/Client#42]
## 🛠 Issue

<img width="562" alt="스크린샷 2023-11-30 오후 2 05 02" src="https://github.com/DO-SOPT-CDS-TEAM-WEB7/Client/assets/109661444/5ce7cd89-5300-40fd-80c9-bc86e8a2a366">
이 부분 API 연결 작업

## 📝 To-do

- [x] API 기본 세팅
- [x] 날짜 더미 데이터 (우선은) 만들어서 요청 보내기
- [x] 기존값 받아온 데이터로 변경
- [x] 항공사 이미지 저장, 동적 렌더링
- [x] 선택된 티켓 저장하기
