### ISSUE TITLE
[Feat] 항공권 리스트 티켓 필터링

### ISSUE THREAD

**Issue by se0jinYoon** [DO-SOPT-CDS-TEAM-WEB7/Client#48]
## 🛠 Issue

<img width="191" alt="스크린샷 2023-12-01 오전 7 36 36" src="https://github.com/DO-SOPT-CDS-TEAM-WEB7/Client/assets/109661444/70ca160b-4a80-4c47-b1f5-ab6caceb0af3">

요 부분 선택한 값에 따라 필터링 되도록 구현하기
## 📝 To-do

- [x] 항공사 드롭다운 클릭 시 서버에서 데이터 받아오기 GET
- [x] input 체크박스 클릭될 때 값 저장하는 state
- [x] 적용하기 누르면 필터링 된 티켓들로만 렌더링
- [x] 드롭다운에서 취소, 적용하기 버튼 누르면 드롭다운 닫히도록 구현
- [x] 항공사 필터링에서 아무것도 선택하지 않을 경우 전체 티켓 렌더링 처리
