### ISSUE TITLE
[Feat] 가격 비교 티켓 내역

### ISSUE THREAD

**Issue by simeunseo** [DO-SOPT-CDS-TEAM-WEB7/Client#50]
## 🛠 Issue

가격 비교 페이지에서 티켓 내역을 렌더링한다.
![image](https://github.com/DO-SOPT-CDS-TEAM-WEB7/Client/assets/55528304/f958cd20-ec9d-43d0-919a-85e39baf9882)

## 📝 To-do

- [ ] 티켓 정보 컴포넌트 제작
- [ ] api 연결 데이터 prop으로 내려서 렌더링
- [ ] 광고 배너 삽입
