### ISSUE TITLE
[Init] 반응형 세팅

### ISSUE THREAD

**Issue by aazkgh** [DO-SOPT-CDS-TEAM-WEB7/Client#7]
## 🛠 Issue

반응형을 적용하기 위한 너비와 정렬 초기 세팅

## 📝 To-do

- [ ] 콘텐츠 사이즈 고정 (여백 조정)
- [ ] body 태그 정렬
- [ ] 특정 너비 아래시 콘텐츠 유지
